### ISSUE TITLE
Release v1.37.2 to npm

### ISSUE THREAD

**Issue by kolomied** [elegantdevelopment/aws-cdk-dynamodb-seeder#24]
**Describe the bug**
Latest version released to npm is 1.37.1 that has a typo which prevents the construct from seeding data successfully.

**To Reproduce**
 - Create a project with latest version of aws-cdk-dynamodb-seeder installed.
 - cdk deploy
 - observe dynamodb table not populated with seed data 

**Expected behavior**
Latest version of the npm module should seed data successfully.

**Comment by jsdtaylor** [comment]
I need to upgrade to latest anyway, so will fix in 1.44.0

**Comment by jsdtaylor** [comment]
Will be fixed by #25

**Comment by jsdtaylor** [comment]
Releasing 1.44.0
